# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

workspace 'YourLine'

project 'YourLine.xcodeproj'
project '../Utility/Utility.xcodeproj'

def ui_pods
  pod 'SDWebImage', '~> 5.0'
  pod 'Instructions', '~> 2.2.0'
  pod 'SideMenu'
  pod "ViewAnimator"
  pod 'NVActivityIndicatorView'
  pod 'SkeletonView'
end

def shared_pods
end

target 'YourLine' do
  project 'YourLine'
  use_frameworks!

  # Pods for YourLine
  pod 'SideMenu'
  pod 'SwiftDate', '~> 5.0'

  target 'YourLineTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YourLineUITests' do
    # Pods for testing
  end

end

# Presentation targets

target 'Presentation' do
  project '../Presentation/Presentation'
  inherit! :search_paths
  use_frameworks!
  
  inhibit_all_warnings!
  
  ui_pods
  
  target 'PresentationTests' do
    inherit! :search_paths
        
    ui_pods
  end
end


# Services targets

target 'Services' do
  project '../Services/Services'
  inherit! :search_paths
  
  use_frameworks!
  
  inhibit_all_warnings!

  target 'ServicesTests' do
    inherit! :search_paths

  end
end

target 'Data' do
  project '../Data/Data'
  inherit! :search_paths
  
  use_frameworks!
    
  inhibit_all_warnings!

  target 'DataTests' do
    inherit! :search_paths

  end
end

target 'Utility' do
  project '../Utility/Utility'
  inherit! :search_paths
  
  use_frameworks!
  
  pod 'SwiftDate', '~> 5.0'
  pod 'SwiftValidator', '3.0.1'
  pod 'KeychainAccess'
  pod 'SwifterSwift'
  pod 'SnapKit', '~> 5.6.0'
  pod 'IQKeyboardManager'

  inhibit_all_warnings!

  target 'UtilityTests' do
    inherit! :search_paths

  end
end

